[tool.poetry]
name = "nislmigrate"
version = "0.0.8"
description = "The tool for migrating SystemLink data."
authors = ["sedwards <shawn.edwards@ni.com>"]

[tool.poetry.dependencies]
python = "^3.6.8"
argparse = "^1.4.0"
pytest = "^6.2.3"
pymongo = "^3.11.3"
tox = "^3.23.0"
bson = "*"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
nislmigrate = 'slmigrate:slmigrate'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length=100