name: Publish Package to PyPI

on:
  release:
    types:
      - published

jobs:
  build-and-publish:
    if: github.repository == 'ni/NI-SystemLink-Migration'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install setuptools and other tools
        run: python3 -m pip install poetry

      - name: Update nislmigrate release version
        run: poetry version $(git describe --tags --abbrev=0)

      - name: Build packages
        run: poetry build

      - name: Publish distribution to PyPI
        if: github.event.action == 'published'
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
